name: Create tag

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/undercurrent-technologies/matching-engine
      IMAGE_TAG: ${{ github.ref_name }}
      GIT_TERMINAL_PROMPT: 1
    
    steps:
      - if: ${{ github.ref_type == 'tag' }}   
        uses: bhowell2/github-substring-action@1.0.2
        id: tag
        with:
          value: ${{ github.ref_name }}
          index_of_str: v

      - name: echo env test
        run: |
          if [ ${{ github.ref_type }} == 'branch' ] && [ ${{ github.ref_name }} == 'main' ]
          then
            echo "Hello main"
          else
            echo ${{ steps.tag.outputs.substring }}
            echo "Hello tag"
          fi
