name: Create tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/undercurrent-technologies/matching-engine
      IMAGE_TAG: ${{ github.ref_name }}
      GIT_TERMINAL_PROMPT: 1
    
    steps:
      - name: substring-action      
        uses: bhowell2/github-substring-action@1.0.2
        id: tag
        with:
          value: ${{ github.ref_name }}
          index_of_str: v
            
      - uses: actions/checkout@v3
      - run: git config --global url.https://${ACCESS_USER}:${ACCESS_TOKEN}@github.com/.insteadOf https://github.com
      # - name: Create new tag
      #   run: git tag v${{ github.event.inputs.tag }}
      # - name: Push new tag
      #   run: git push origin v${{ github.event.inputs.tag }}
      - name: echo env test
        run: |
          echo ${IMAGE_NAME}:${IMAGE_TAG}
          echo ${{ steps.tag.outputs.substring }}
