name: Versioning Control

on: 
  workflow_dispatch:
    inputs:
      tag: 
        description: 'New tag name'
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/undercurrent-technologies/matching-engine
      IMAGE_TAG: ${{ github.event.inputs.tag }}
      GIT_TERMINAL_PROMPT: 1
    
    steps:
      - uses: actions/checkout@v3
      - run: git config --global url.https://${ACCESS_USER}:${ACCESS_TOKEN}@github.com/.insteadOf https://github.com
      - name: Create new tag
        run: git tag v${{ github.event.inputs.tag }}
      - name: echo env test
        run: |
          echo ${IMAGE_NAME}
          echo v${IMAGE_TAG}
          echo ${IMAGE_NAME}:${IMAGE_TAG}
